// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "fs": Application User Types
//
// Command:
// $ goagen
// --design=github.com/sky0621/try-goa/fs
// --out=$(GOPATH)\src\github.com\sky0621\try-goa
// --version=v1.3.0

package client
