// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/sky0621/try-goa/design
// --out=$(GOPATH)\src\github.com\sky0621\try-goa
// --version=v1.3.1

package client
