consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Movie:
    description: Movie Response Type (default view)
    example:
      movieId: 8.4600894e+18
      movieName: Reiciendis ut odio voluptatem saepe quis voluptate.
    properties:
      movieId:
        description: Unique Movie ID
        example: 8.4600894e+18
        format: int64
        type: integer
      movieName:
        description: Movie Name
        example: Reiciendis ut odio voluptatem saepe quis voluptate.
        type: string
    required:
    - movieId
    - movieName
    title: 'Mediatype identifier: application/vnd.movie+json; view=default'
    type: object
host: localhost:8585
info:
  description: A simple movie
  title: Fan Movie
  version: ""
paths:
  /movies/{movieId}:
    get:
      description: Get 1 Movie Information
      operationId: movie#show
      parameters:
      - description: Unique Movie ID
        in: path
        name: movieId
        required: true
        type: integer
      produces:
      - application/vnd.movie+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Movie'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show movie
      tags:
      - movie
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Movie'
schemes:
- http
swagger: "2.0"
