// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "fs": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/sky0621/try-goa/fs
// --out=$(GOPATH)\src\github.com\sky0621\try-goa
// --version=v1.3.0

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// MovieController is the controller interface for the Movie actions.
type MovieController interface {
	goa.Muxer
	Show(*ShowMovieContext) error
}

// MountMovieController "mounts" a Movie resource controller on the given service.
func MountMovieController(service *goa.Service, ctrl MovieController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewShowMovieContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Show(rctx)
	}
	service.Mux.Handle("GET", "/movies/:movieId", ctrl.MuxHandler("show", h, nil))
	service.LogInfo("mount", "ctrl", "Movie", "action", "Show", "route", "GET /movies/:movieId")
}
