// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "fs": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/sky0621/try-goa/fs
// --out=$(GOPATH)\src\github.com\sky0621\try-goa
// --version=v1.3.0

package app

import (
	"fmt"
	"strings"
)

// MovieHref returns the resource href.
func MovieHref(movieID interface{}) string {
	parammovieID := strings.TrimLeftFunc(fmt.Sprintf("%v", movieID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/movies/%v", parammovieID)
}
